export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_REQUEST'
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS'
export const RESTAURANT_LIST_FAIL = 'RESTAURANT_LIST_FAIL'

export const RESTAURANT_CREATE_REQUEST = 'RESTAURANT_CREATE_REQUEST'
export const RESTAURANT_CREATE_SUCCESS = 'RESTAURANT_CREATE_SUCCESS'
export const RESTAURANT_CREATE_FAIL = 'RESTAURANT_CREATE_FAIL'

export const RESTAURANT_EDIT_REQUEST = 'RESTAURANT_EDIT_REQUEST'
export const RESTAURANT_EDIT_SUCCESS = 'RESTAURANT_EDIT_SUCCESS'
export const RESTAURANT_EDIT_FAIL = 'RESTAURANT_EDIT_FAIL'

export const RESTAURANT_DELETE_REQUEST = 'RESTAURANT_DELETE_REQUEST'
export const RESTAURANT_DELETE_SUCCESS = 'RESTAURANT_DELETE_SUCCESS'
export const RESTAURANT_DELETE_FAIL = 'RESTAURANT_DELETE_FAIL'
